### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by yindashan** [open-falcon/aggregator#1]
package cron

func compute(operands []string, operators []uint8, hostname string, valMap map[string]float64) (val float64, valid bool) {
    count := len(operands)
    if count == 0 {
        return val, false
    }

```
vals := queryOperands(operands, hostname, valMap)
if len(vals) != count {
    return val, false
}

val = vals[0]

for i := 1; i < count; i++ {
    if operators[i] == '+' {
        val += vals[i]
    } else {
        val -= vals[i]
    }
}

return val, true
```

}
这个代码块中的下面的代码有些问题：
for i := 1; i < count; i++ {
        if operators[i] == '+' {
            val += vals[i]
        } else {
            val -= vals[i]
        }
    }

operators[i]改为operators[i-1]

**Comment by UlricQin** [comment]
https://github.com/open-falcon/aggregator/commit/598e39b71626b4766455dd1fd6138cb3db8c585a

**Comment by laiwei** [comment]
@yindashan :+1:
